name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: SCP Command to Transfer Files
      uses: appleboy/scp-action@v0.1.1
      env:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}        
        key: ${{ secrets.KEY }}
      with:
        source: "."
        target: "/var/test"
